Abdelrhman: Fix mongoDB roadmap performance optimiaztion section
kamranahmedse/developer-roadmap pull request #4629
Opened 2023-10-25 08:00 UTC by AbdelrhmanX7

Fix
 1- when user mark Query Operators as Done it makes Performance Optimization as Done also
 2- when user click on "Performance Optimization" it opened "Query Operators" side panel (we don't have content for Performance Optimization)
 3- split Performance Optimization into another folder called 105-performance-optimization before it was under 105-query-operators

2023-10-25 08:09 UTC, kamranahmedse requested changes

2023-10-25 08:09 UTC, kamranahmedse commented on src/components/TopicDetail/TopicProgressButton.tsx
> +        />
Can you please revert the changes in this file

2023-10-25 08:09 UTC, AbdelrhmanX7 commented on src/components/TopicDetail/TopicProgressButton.tsx
> +        />
Sure i will do that rn

2023-10-25 08:11 UTC, AbdelrhmanX7 commented on src/components/TopicDetail/TopicProgressButton.tsx
> +        />
Done

2023-10-25 08:42 UTC, merged

2023-10-25 08:42 UTC, kamranahmedse commented
Thank you!

2023-11-10 08:16 UTC, 841372 commented on src/components/TopicDetail/TopicProgressButton.tsx
> +        />
> بالتأكيد سأفعل ذلك rn