Update 100-context.md
kamranahmedse/developer-roadmap pull request #5033
Opened 2024-01-15 06:50 UTC by Yubraj977

This article help me  a lot to grab the idea about how the context is solving the problem of the prop drilling. I think beginner should start with this article to grasp the knowledge about the problem that trying to solve by the the context

2024-01-15 07:55 UTC, Mohitbishukarma reviewed
That is nice article 👍👍

2024-01-17 07:47 UTC, san-poon reviewed
https://www.w3schools.com/react/react_usecontext.asp, this site just confuse the newcomers.

2024-01-17 11:48 UTC, Yubraj977 commented
> https://www.w3schools.com/react/react_usecontext.asp, this site just confuse the newcomers.

Maybe for you it created a confusions but for me this is the article that make me clearly understand what is the problem with normal props and when we should avoid prop drilling

2024-05-10 09:07 UTC, dansholds requested changes

2024-05-10 09:07 UTC, dansholds commented on src/data/roadmaps/react/content/106-state-management/100-context.md
> +- [Basic react use context ](https://www.w3schools.com/react/react_usecontext.asp)
please remove the whitespace after context and change the title to "Basic useContext Guide" or something of that nature.

2024-05-11 01:00 UTC, kamranahmedse commented on src/data/roadmaps/react/content/106-state-management/100-context.md
> +
```suggestion
```

2024-05-11 01:00 UTC, kamranahmedse commented on src/data/roadmaps/react/content/106-state-management/100-context.md
> +- [Basic react use context ](https://www.w3schools.com/react/react_usecontext.asp)
```suggestion
- [Basic useContext Guide](https://www.w3schools.com/react/react_usecontext.asp)
```

2024-05-11 01:00 UTC, merged