Update index.md
kamranahmedse/developer-roadmap pull request #5143
Opened 2024-02-05 19:34 UTC by bravo1goingdark

added correct syntax for renaming table or column

2024-05-10 10:18 UTC, dansholds requested changes
Please fix the comment I made!

In future please try to write a more descriptive PR title i.e. "Add this to that"

2024-05-10 10:18 UTC, dansholds commented on src/data/roadmaps/sql/content/102-ddl/index.md
> +
Please remove this whitespace, apart from that LGTM!

2024-05-11 01:03 UTC, kamranahmedse commented on src/data/roadmaps/sql/content/102-ddl/index.md
> +
```suggestion
```

2024-05-11 01:04 UTC, kamranahmedse commented on src/data/roadmaps/sql/content/102-ddl/index.md
> +
```suggestion
```

2024-05-11 01:04 UTC, kamranahmedse commented on src/data/roadmaps/sql/content/102-ddl/index.md
> +    ```sql
```suggestion
   ; To rename a column
```

2024-05-11 01:05 UTC, kamranahmedse commented on src/data/roadmaps/sql/content/102-ddl/index.md
> +   ; To rename a column
```suggestion
  -- To rename a column
```

2024-05-11 01:05 UTC, kamranahmedse commented on src/data/roadmaps/sql/content/102-ddl/index.md
> +    RENAME COLUMN old_column_name TO new_column_name;
```suggestion
    -- To rename a table
    ALTER TABLE table_name
    RENAME TO new_table_name;
    
    -- To rename a column
    ALTER TABLE table_name
    RENAME COLUMN old_column_name TO new_column_name;
```

2024-05-11 01:05 UTC, merged