Update 103-oop-basics.md
kamranahmedse/developer-roadmap pull request #5342
Opened 2024-03-13 12:47 UTC by mishra-naveen-dev

add some basic concept topic

2024-05-10 11:14 UTC, dansholds requested changes
In future please try to write a more descriptive PR title i.e. "Add this to that"

2024-05-10 11:14 UTC, dansholds commented on src/data/roadmaps/datastructures-and-algorithms/content/101-programming-fundamentals/103-oop-basics.md
> +## OOP Basics
remove the extra #

2024-05-10 11:14 UTC, dansholds commented on src/data/roadmaps/datastructures-and-algorithms/content/101-programming-fundamentals/103-oop-basics.md
> +# There are some basic concepts that act as the building blocks of OOPs i.e.
Make this a markdown list rather than a header & remove `i.e.` from the end

2024-05-11 01:11 UTC, closed without merging

2024-05-11 02:13 UTC, mishra-naveen-dev commented on src/data/roadmaps/datastructures-and-algorithms/content/101-programming-fundamentals/103-oop-basics.md
> +## OOP Basics
Alright, I will fix it.

2024-05-11 02:13 UTC, mishra-naveen-dev commented on src/data/roadmaps/datastructures-and-algorithms/content/101-programming-fundamentals/103-oop-basics.md
> +# There are some basic concepts that act as the building blocks of OOPs i.e.
Alright, I will fix it. I am grateful for your guidance.