Update 100-kotlin.md
kamranahmedse/developer-roadmap pull request #5351
Opened 2024-03-15 12:42 UTC by SaktiSriraj

Resources to learn Kotlin were added

2024-05-10 11:25 UTC, dansholds requested changes
Good contribution overall but please remediate my comments.

In future please try to write a more descriptive PR title i.e. "Add this to that"

2024-05-10 11:25 UTC, dansholds commented on src/data/roadmaps/android/content/100-pick-a-language/100-kotlin.md
> +[Learn Kotlin - w3schools](https://www.w3schools.com/kotlin/)
Remove the line break and indent with a hyphen

 ```suggestion
- [Learn Kotlin Programming for Beginners - Free Code Camp](https://youtu.be/EExSSotojVI?si=4VPW8ZHa2UMX0HH1)
- [Learn Kotlin - w3schools](https://www.w3schools.com/kotlin/)
```

2024-05-10 16:29 UTC, SaktiSriraj commented on src/data/roadmaps/android/content/100-pick-a-language/100-kotlin.md
> +[Learn Kotlin - w3schools](https://www.w3schools.com/kotlin/)
Okay. Will keep that in mind

2024-05-11 01:13 UTC, kamranahmedse commented on src/data/roadmaps/android/content/100-pick-a-language/100-kotlin.md
> +## Useful Resources
```suggestion
Use following resources to learn more:
```

2024-05-11 01:13 UTC, merged