Add how to become devops engineer guide
kamranahmedse/developer-roadmap pull request #5847
Opened 2024-06-10 16:34 UTC by dansholds

Added new guide "How to become DevOps Engineer in 2024.

Set date as tomorrow as it's late in the day.

https://github.com/kamranahmedse/developer-roadmap/assets/25537601/919ebd05-bea0-44ef-8bae-850ddf4e5a00

2024-06-10 20:37 UTC, kamranahmedse requested changes

2024-06-10 20:37 UTC, kamranahmedse commented on src/data/guides/how-to-become-devops-engineer.md
> +The internet is full of resources for learning DevOps and DevOps tools. Many of these guides lack structure and organization, resulting in a dilemma of where to start. To help beginners learn DevOps
```suggestion
The internet is full of resources for learning DevOps and DevOps tools. Many of these guides lack structure and organization, resulting in a dilemma of where to start. To help beginners learn DevOps in a structured manner, [roadmap.sh](https://roadmap.sh) has a beginner-friendly [DevOps roadmap](https://roadmap.sh/devops?r=devops-beginner). 
```

2024-06-10 20:37 UTC, kamranahmedse commented on src/data/guides/how-to-become-devops-engineer.md
> +DevOps combines development and operations to automate software delivery. To become a DevOps engineer, you should adopt a mindset of automation, risk awareness, systems thinking, and continuous learn
I don't think it makes sense to have `h2` for TL;DR:`. I would change it to simple bold:

```suggestion
**TL;DR:** DevOps combines development and operations to automate software delivery. To become a DevOps engineer, you should adopt a mindset of automation, risk awareness, systems thinking, and continuous learning. In addition to the mindset, follow the steps below:
```

2024-06-10 20:37 UTC, kamranahmedse commented on src/data/guides/how-to-become-devops-engineer.md
> +### Solid programming fundamentals
Nitpick: we have a linting style to always add an empty line before and after headings

```suggestion
### Solid programming fundamentals

```

2024-06-10 20:37 UTC, kamranahmedse commented on src/data/guides/how-to-become-devops-engineer.md
> +
One empty line at most.

```suggestion

```

2024-06-10 20:37 UTC, kamranahmedse commented on src/data/guides/how-to-become-devops-engineer.md
> +Alternatively, you could demonstrate your understanding by taking the [certification exam from AWS](https://aws.amazon.com/certification/?trk=dc557659-52ab-4a28-b2b8-0b1fb90235db&sc_channel=ps&ef_id=
```suggestion
Alternatively, you could demonstrate your understanding by taking the [certification exam from AWS](https://aws.amazon.com/certification/).
```

2024-06-11 09:47 UTC, kamranahmedse commented on src/data/guides/how-to-become-devops-engineer.md
> +### Solid programming fundamentals
This needs to be applied to all the headings.

2024-06-11 09:52 UTC, dansholds commented on src/data/guides/how-to-become-devops-engineer.md
> +### Solid programming fundamentals
Done 👍

2024-06-11 09:55 UTC, dansholds commented on src/data/guides/how-to-become-devops-engineer.md
> +
applied throughout

2024-06-11 09:56 UTC, merged