Update 103-data-transformation.md
kamranahmedse/developer-roadmap pull request #5855
Opened 2024-06-11 21:24 UTC by Wblake95

Descriptive article that breaks down the process.
Additionally, links to examples in Python and R

2024-06-12 08:29 UTC, dansholds requested changes

2024-06-12 08:29 UTC, dansholds commented on src/data/roadmaps/data-analyst/content/107-data-cleaning/103-data-transformation.md
> +- [@article@What is Data Transformation - Geeks for Geeks](https://www.geeksforgeeks.org/what-is-data-transformation/)
```suggestion
Data Transformation, also known as Data Wrangling, is an essential part of a Data Analyst's role. This process involves the conversion of data from a raw format into another format to make it more appropriate and valuable for a variety of downstream purposes such as analytics. Data Analysts transform data to make the data more suitable for analysis, ensure accuracy, and to improve data quality. The right transformation techniques can give the data a structure, multiply its value, and enhance the accuracy of the analytics performed by serving meaningful results.

Learn more from the following resources:

- [@article@What is Data Transformation?](https://www.geeksforgeeks.org/what-is-data-transformation/)
```

2024-06-12 08:29 UTC, dansholds commented on src/data/roadmaps/data-analyst/content/107-data-cleaning/103-data-transformation.md
> +- [@article@What is Data Transformation - Geeks for Geeks](https://www.geeksforgeeks.org/what-is-data-transformation/)
You mention in your PR description that you've added links to Python and R examples but I don't see them?

2024-06-12 14:02 UTC, Wblake95 reviewed
Sorry for my mistake

2024-06-14 08:16 UTC, dansholds requested changes
I've found interesting alternative links to the ones you have, we already have a lot of links to this site throughout roadmap.sh so it's nice to expose our users to other sites and creators 😄

2024-06-14 08:16 UTC, dansholds commented on src/data/roadmaps/data-analyst/content/107-data-cleaning/103-data-transformation.md
> +- [@article@What is Data Transformation - Geeks for Geeks](https://www.geeksforgeeks.org/what-is-data-transformation/)
```suggestion
- [@article@What is Data Transformation](https://www.tibco.com/glossary/what-is-data-transformation)
```

2024-06-14 08:16 UTC, dansholds commented on src/data/roadmaps/data-analyst/content/107-data-cleaning/103-data-transformation.md
> +- [@article@Example with Python](https://www.geeksforgeeks.org/time-series-data-transformation-using-python/)
```suggestion
- [@article@Transforming Data with Python](https://www.udacity.com/blog/2023/01/transforming-data-with-python.html)
```

2024-06-14 08:16 UTC, dansholds commented on src/data/roadmaps/data-analyst/content/107-data-cleaning/103-data-transformation.md
> +- [@article@Example with R](https://www.geeksforgeeks.org/data-cleaning-transformation-with-dplyr-in-r/)
```suggestion
- [@article@Data Transformation with R](https://r4ds.had.co.nz/transform.html)
```

2024-06-14 19:41 UTC, Wblake95 commented
Those sound great!  I have never heard of tibco or r4ds.

2024-06-14 21:01 UTC, dansholds approved these changes

2024-06-14 21:01 UTC, merged