feat: daily.dev links
kamranahmedse/developer-roadmap pull request #5860
Opened 2024-06-12 14:58 UTC by capJavert

- added links to daily.dev pages that match topic subject
- added `daily.dev` link type (let me know if that is alright)

2024-06-12 15:00 UTC, capJavert commented on src/data/roadmaps/ai-data-scientist/content/ab-testing.md
> +- [@daily.dev@Explore the top posts about ab-testing on daily.dev](https://app.daily.dev/tags/ab-testing?ref=roadmapsh)
Noticed some topic pages do not have "Visit the following resources to learn more" section with links so I added to the last link list I found in the markdown. 

If you want I can alternatively add that kind of section to all pages that are missing it and then add daily.dev link there?

2024-06-12 15:03 UTC, capJavert commented on src/components/TopicDetail/TopicDetail.tsx
> +  'daily.dev': "bg-[#ce3df3] text-white"
daily.dev custom color, let me know if there is a better place to add to tailwind config.

2024-06-12 15:47 UTC, dansholds commented
@capJavert just leaving an initial comment to let you know that I'm reviewing this, it's just big 😂

2024-06-12 22:41 UTC, kamranahmedse commented on src/components/TopicDetail/TopicDetail.tsx
> +  'daily.dev': "bg-[#ce3df3] text-white"
We were planning to add `feed` badge instead to make it more clear what the contents of link are. We can keep the syltes, just replace `daily.dev` with `feed`

2024-06-12 22:44 UTC, kamranahmedse commented on src/data/roadmaps/aspnet-core/content/107-databases/102-relational/102-mariadb.md
> +- [@daily.dev@Explore the top posts about infrastructure on daily.dev](https://app.daily.dev/tags/infrastructure?ref=roadmapsh)
I don't think this should be linking to infrastructure tag

2024-06-13 00:13 UTC, kamranahmedse requested changes

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/software-architect/content/111-web-and-mobile/100-reactive-functional-programming.md
> +- [@daily.dev@Explore the top posts about general-programming on daily.dev](https://app.daily.dev/tags/general-programming?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/software-architect/content/111-web-and-mobile/102-spa-ssr-ssg.md
> +- [@daily.dev@Explore the top posts about webdev on daily.dev](https://app.daily.dev/tags/webdev?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/software-architect/content/116-enterprise-software/103-ibm-bpm.md
> +- [@daily.dev@Explore the top posts about ibm on daily.dev](https://app.daily.dev/tags/ibm?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/software-design-architecture/content/100-clean-code-principles/110-keep-tests-independent.md
> +- [@daily.dev@Explore the top posts about testing on daily.dev](https://app.daily.dev/tags/testing?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/software-design-architecture/content/101-programming-paradigms/102-object-oriented-programming.md
> +- [@daily.dev@Explore the top posts about general-programming on daily.dev](https://app.daily.dev/tags/general-programming?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/software-design-architecture/content/102-object-oriented-programming/100-primary-principles/103-encapsulation.md
> +- [@daily.dev@Explore the top posts about general-programming on daily.dev](https://app.daily.dev/tags/general-programming?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/software-design-architecture/content/107-architectural-patterns/101-soa.md
> +- [@daily.dev@Explore the top posts about architecture on daily.dev](https://app.daily.dev/tags/architecture?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/software-design-architecture/content/107-architectural-patterns/107-serverless-architecture.md
> +- [@daily.dev@Explore the top posts about architecture on daily.dev](https://app.daily.dev/tags/architecture?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/software-design-architecture/content/107-architectural-patterns/109-event-sourcing.md
> +- [@daily.dev@Explore the top posts about architecture on daily.dev](https://app.daily.dev/tags/architecture?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/software-design-architecture/content/108-enterprise-patterns/index.md
> +- [@daily.dev@Explore the top posts about enterprise on daily.dev](https://app.daily.dev/tags/enterprise?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/spring-boot/content/107-spring-data/101-spring-data-mongodb.md
> +- [@daily.dev@Explore the top posts about mongodb on daily.dev](https://app.daily.dev/tags/mongodb?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/spring-boot/content/108-microservices/100-spring-cloud/100-spring-cloud-gateway.md
> +- [@daily.dev@Explore the top posts about cloud on daily.dev](https://app.daily.dev/tags/cloud?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/spring-boot/content/108-microservices/100-spring-cloud/101-cloud-config.md
> +- [@daily.dev@Explore the top posts about cloud on daily.dev](https://app.daily.dev/tags/cloud?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/spring-boot/content/108-microservices/100-spring-cloud/102-spring-cloud-circuit-breaker.md
> +- [@daily.dev@Explore the top posts about cloud on daily.dev](https://app.daily.dev/tags/cloud?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/spring-boot/content/108-microservices/100-spring-cloud/103-spring-cloud-openfeign.md
> +- [@daily.dev@Explore the top posts about cloud on daily.dev](https://app.daily.dev/tags/cloud?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/spring-boot/content/109-spring-mvc/index.md
> +- [@daily.dev@Explore the top posts about spring on daily.dev](https://app.daily.dev/tags/spring?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/spring-boot/content/102-spring-boot-starters.md
> +- [@daily.dev@Explore the top posts about spring on daily.dev](https://app.daily.dev/tags/spring?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/spring-boot/content/104-spring-boot-actuators.md
> +- [@daily.dev@Explore the top posts about spring on daily.dev](https://app.daily.dev/tags/spring?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/system-design/content/109-load-balancers/103-load-balancing-algorithms.md
> +- [@daily.dev@Explore the top posts about algorithms on daily.dev](https://app.daily.dev/tags/algorithms?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/system-design/content/110-application-layer/101-service-discovery.md
> +- [@daily.dev@Explore the top posts about architecture on daily.dev](https://app.daily.dev/tags/architecture?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/system-design/content/111-databases/index.md
> +- [@daily.dev@Explore the top posts about backend on daily.dev](https://app.daily.dev/tags/backend?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/system-design/content/115-communication/103-rpc.md
> +- [@daily.dev@Explore the top posts about backend on daily.dev](https://app.daily.dev/tags/backend?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/system-design/content/117-monitoring/104-usage-monitoring.md
> +- [@daily.dev@Explore the top posts about monitoring on daily.dev](https://app.daily.dev/tags/monitoring?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/system-design/content/117-monitoring/102-performance-monitoring.md
> +- [@daily.dev@Explore the top posts about monitoring on daily.dev](https://app.daily.dev/tags/monitoring?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/system-design/content/118-cloud-design-patterns/101-data-management/102-event-sourcing.md
> +- [@daily.dev@Explore the top posts about architecture on daily.dev](https://app.daily.dev/tags/architecture?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/system-design/content/118-cloud-design-patterns/102-design-and-implementation/111-sidecar.md
> +- [@daily.dev@Explore the top posts about infrastructure on daily.dev](https://app.daily.dev/tags/infrastructure?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/system-design/content/118-cloud-design-patterns/103-reliability-patterns/101-high-availability/deployment-stamps.md
> +- [@daily.dev@Explore the top posts about cicd on daily.dev](https://app.daily.dev/tags/cicd?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/typescript/content/100-typescript/103-running-typescript/101-ts-node.md
> +- [@daily.dev@Explore the top posts about typescript on daily.dev](https://app.daily.dev/tags/typescript?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/typescript/content/100-typescript/103-running-typescript/102-ts-playground.md
> +- [@daily.dev@Explore the top posts about typescript on daily.dev](https://app.daily.dev/tags/typescript?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/typescript/content/100-typescript/103-running-typescript/index.md
> +- [@daily.dev@Explore the top posts about typescript on daily.dev](https://app.daily.dev/tags/typescript?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/typescript/content/101-typescript-types/index.md
> +- [@daily.dev@Explore the top posts about typescript on daily.dev](https://app.daily.dev/tags/typescript?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/typescript/content/114-ecosystem/103-build-tools.md
> +- [@daily.dev@Explore the top posts about tools on daily.dev](https://app.daily.dev/tags/tools?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/vue/content/100-fundamental-topics/104-api-styles/101-composition-api.md
> +- [@daily.dev@Explore the top posts about vuejs on daily.dev](https://app.daily.dev/tags/vuejs?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/vue/content/100-fundamental-topics/100-create-vue.md
> +- [@daily.dev@Explore the top posts about vuejs on daily.dev](https://app.daily.dev/tags/vuejs?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/vue/content/100-fundamental-topics/108-lifecycle-hooks.md
> +- [@daily.dev@Explore the top posts about react-hooks on daily.dev](https://app.daily.dev/tags/react-hooks?ref=roadmapsh)
Not relevant, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/vue/content/102-ecosystem/100-routing/100-vue-router.md
> +- [@daily.dev@Explore the top posts about vuejs on daily.dev](https://app.daily.dev/tags/vuejs?ref=roadmapsh)
Not relevant, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/vue/content/102-ecosystem/108-vue-testing-library.md
> +- [@daily.dev@Explore the top posts about testing on daily.dev](https://app.daily.dev/tags/testing?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:13 UTC, kamranahmedse commented on src/data/roadmaps/vue/content/102-ecosystem/111-vuetify.md
> +- [@daily.dev@Explore the top posts about vuejs on daily.dev](https://app.daily.dev/tags/vuejs?ref=roadmapsh)
Not relevant enough, let's remove it please.

2024-06-13 00:19 UTC, kamranahmedse commented
Thank you for the PR, @capJavert! I have left comments on the places where feed links do not make sense. 

Mainly, we should aim to link to the daily.dev feed from the parent nodes and not specific topics. For example, in the case of the JavaScript roadmap, linking to the daily.dev JavaScript feed makes sense from the introductory nodes (i.e., introduction, what, why, history, etc.) but not from specific topics (e.g., variable declaration, bundling, etc.) unless you have a feed for that specific topic.

Let's wait for @dansholds to finish his review as well, and then you can continue with the changes.

2024-06-13 09:13 UTC, dansholds commented on src/components/TopicDetail/TopicDetail.tsx
> +  'daily.dev': "bg-[#ce3df3] text-white"
+1, replace with `feed`

2024-06-13 09:23 UTC, dansholds requested changes

2024-06-13 09:23 UTC, dansholds commented on src/components/TopicDetail/TopicDetail.tsx
> +              const order = ['official', 'opensource', 'article', 'video', 'daily.dev'];
Again, replace with `feed`

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/ai-data-scientist/content/hypothesis-testing.md
> +- [@daily.dev@Explore the top posts about testing on daily.dev](https://app.daily.dev/tags/testing?ref=roadmapsh)
Too broad, remove.

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/ai-data-scientist/content/linear-algebra-calc-mathana.md
> +- [@daily.dev@Explore the top posts about math on daily.dev](https://app.daily.dev/tags/math?ref=roadmapsh)
Too broad, remove.

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/ai-data-scientist/content/probability-sampling.md
> +- [@daily.dev@Explore the top posts about statistics on daily.dev](https://app.daily.dev/tags/statistics?ref=roadmapsh)
Too broad, remove

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/angular/content/100-typescript-basics/101-why-use-typescript.md
> +- [@daily.dev@Explore the top posts about typescript on daily.dev](https://app.daily.dev/tags/typescript?ref=roadmapsh)
Remove, lets not add the same daily.dev feed to every typescript topic (this goes for all other topics also!)

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/angular/content/100-typescript-basics/index.md
> +- [@daily.dev@Explore the top posts about typescript on daily.dev](https://app.daily.dev/tags/typescript?ref=roadmapsh)
Remove

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/angular/content/101-rxjs-basics/103-rxjs-vs-promises.md
> +- [@daily.dev@Explore the top posts about rxjs on daily.dev](https://app.daily.dev/tags/rxjs?ref=roadmapsh)
+1

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/angular/content/102-angular-basics/101-angular-components.md
> +- [@daily.dev@Explore the top posts about angular on daily.dev](https://app.daily.dev/tags/angular?ref=roadmapsh)
remove

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/angular/content/102-angular-basics/102-angular-templates.md
> +- [@daily.dev@Explore the top posts about angular on daily.dev](https://app.daily.dev/tags/angular?ref=roadmapsh)
remove

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/angular/content/102-angular-basics/103-angular-modules.md
> +- [@daily.dev@Explore the top posts about angular on daily.dev](https://app.daily.dev/tags/angular?ref=roadmapsh)
remove

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/angular/content/103-angular-cli/104-ng-e2e.md
> +- [@daily.dev@Explore the top posts about testing on daily.dev](https://app.daily.dev/tags/testing?ref=roadmapsh)
This feed is about testing in general, not angular e2e testing, remove.

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/angular/content/103-angular-cli/index.md
> +- [@daily.dev@Explore the top posts about angular on daily.dev](https://app.daily.dev/tags/angular?ref=roadmapsh)
remove, feed not about angular cli

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/angular/content/113-angular-ssr/100-angular-universal.md
> +- [@daily.dev@Explore the top posts about angular on daily.dev](https://app.daily.dev/tags/angular?ref=roadmapsh)
Not relevant to Angular universal, remove

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/angular/content/113-angular-ssr/index.md
> +- [@daily.dev@Explore the top posts about angular on daily.dev](https://app.daily.dev/tags/angular?ref=roadmapsh)
not relevant to ssr, remove

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/api-design/content/api-security@qIJ6dUppjAjOTA8eQbp0n.md
> +- [@daily.dev@Explore the top posts about security on daily.dev](https://app.daily.dev/tags/security?ref=roadmapsh)
way too broad, this is API security, not security as a general topic.

2024-06-13 09:23 UTC, dansholds commented on src/data/roadmaps/aspnet-core/content/101-general-development-skills/101-azure-devops-services.md
> +- [@daily.dev@Explore the top posts about azure on daily.dev](https://app.daily.dev/tags/azure?ref=roadmapsh)
Azure is not Azure DevOps, remove or find a more relevant feed tag

2024-06-13 09:36 UTC, dansholds commented
@capJavert I've stopped reviewing after only 2 roadmaps.

**Please manually review all the additions that you've requested and _please_ ensure the following across the entire PR**

1. In regards to the new tag, change it from `@daily.dev@` to `@feed@`
2. In regards to the copy added when you add a link to daily.dev, please change it from `Explore the top posts about azure on daily.dev` to `Explore top posts about <topic>`. We like daily.dev but there's no need to mention the name across 1024 files!
3. Please correct **all** capitalisation and hyphenation in regards to tools, languages and frameworks i.e. `ab-testing` should be `A/B Testing`
4. A single feed does not need adding to more than one location _**unless**_ it's `python` (as an example) in which case it can be added to the `python` roadmap and any other roadmaps that mention **learning python**. such as the data science roadmap.
5. Again, a single feed i.e. `angular` does not need adding 21 times to the Angular roadmap. One is enough in the introduction topic (or similar topic at the **start** of the roadmap)

Also ensure you have corrected any of @kamranahmedse comments if they aren't covered by mine.

**Please** take the time to re-review this PR and action my points, in the automated state that it's in, it's simply too large and has too many issues to be reviewed manually.

2024-06-17 09:33 UTC, dansholds commented
@capJavert Can you please confirm that you've seen this 🤙

2024-06-17 09:51 UTC, capJavert commented
@dansholds yeah, I seen it, I did an update on points 1-3. from your review currently.

2024-06-19 14:58 UTC, merged