Update 101-length.md
kamranahmedse/developer-roadmap pull request #5893
Opened 2024-06-19 14:39 UTC by karim1safan

adding the different between **`LENGTH()`** and **`CHAR_LENGTH()`** In MySQL with examples

2024-06-19 14:44 UTC, dansholds requested changes

2024-06-19 14:44 UTC, dansholds commented on src/data/roadmaps/sql/content/108-advanced-sql-functions/101-string/101-length.md
>  Consider an "employees" table:
This should now be on line 26, not within the code example.

2024-06-19 14:44 UTC, dansholds commented on src/data/roadmaps/sql/content/108-advanced-sql-functions/101-string/101-length.md
> +The `LENGTH()` function in MySQL is a useful tool for working with strings, particularly when dealing with byte-level operations. It is crucial to understand the difference between byte length and ch
This can probably be explained easier via adding links to content that explains the difference between `LENGTH()` & 'CHAR_LENGTH()`.

To do this, remove your additions and simply add:

```
Learn more from the following resources:

- [@article@Article Title](https://article.com)
```

2024-06-24 09:03 UTC, kamranahmedse commented
Thank you for the PR, but we are intentionally keeping this section short. We will be removing these detailed descriptions and replacing it with one short paragraph and external resources to learn.

2024-06-24 09:03 UTC, closed without merging