Add Content links to 'Vue' Section
kamranahmedse/developer-roadmap pull request #5934
Opened 2024-06-26 04:17 UTC by yenaingtun-dev

2024-06-26 07:45 UTC, dansholds commented
@yenaingtun-dev the additions you've made are fine but you've also commited the package.json, so remove that from the PR please.

2024-06-26 08:02 UTC, yenaingtun-dev commented
@dansholds  i have remove it.

2024-06-26 08:57 UTC, dansholds requested changes
One final change 👍

2024-06-26 08:57 UTC, dansholds commented on src/data/roadmaps/vue/content/102-ecosystem/100-routing/100-vue-router.md
> +- [@video@The Vue Router](https://www.youtube.com/watch?v=juocv4AtrHo&t=313s)
lets remove the time stamp for this link as it randomly puts the users at 313 seconds into the video

```suggestion
- [@video@The Vue Router](https://www.youtube.com/watch?v=juocv4AtrHo)
```

2024-06-26 09:13 UTC, yenaingtun-dev commented on src/data/roadmaps/vue/content/102-ecosystem/100-routing/100-vue-router.md
> +- [@video@The Vue Router](https://www.youtube.com/watch?v=juocv4AtrHo&t=313s)
i removed that time stamp from the link and sorry about that.

2024-06-27 08:33 UTC, dansholds approved these changes
Thanks for fixing

2024-06-27 08:34 UTC, merged