Java roadmap: jvm clarifications
kamranahmedse/developer-roadmap pull request #5945
Opened 2024-06-26 13:31 UTC by leni-kirilov

removed duplicate link
added JVM languages and GraalVM as a popular alternative

2024-06-27 08:45 UTC, dansholds requested changes

2024-06-27 08:45 UTC, dansholds commented on src/data/roadmaps/java/content/101-java-advanced-topics/106-how-jvm-works.md
> +Multiple JVM implementations exist, each with unique features. Oracle's HotSpot is the standard implementation, while GraalVM is a high-performance alternative that's gaining popularity. GraalVM offe
Can we try to condense all of this down into one paragraph. The new style guide we have for roadmap copy is less copy, more links 👍

2024-06-27 08:45 UTC, dansholds commented on src/data/roadmaps/java/content/101-java-advanced-topics/106-how-jvm-works.md
> +- [@article@What is JVM & architectyre?](https://www.geeksforgeeks.org/jvm-works-jvm-architecture/)
Typo in `architecture` & try to find another link other than the geeksforgeeks one, we already have 130+ links for that site so it's nice to add more diversity for our users 👍

2024-06-27 09:00 UTC, leni-kirilov commented on src/data/roadmaps/java/content/101-java-advanced-topics/106-how-jvm-works.md
> +- [@article@What is JVM & architectyre?](https://www.geeksforgeeks.org/jvm-works-jvm-architecture/)
ok I'll look for another one, but I read it yesterday and it seemed good. Definitely better than the existing one which is pre Java8 and doesn't mention a lot of things

2024-07-01 09:32 UTC, dansholds commented on src/data/roadmaps/java/content/101-java-advanced-topics/106-how-jvm-works.md
> +- [@article@ GraalVM](https://www.graalvm.org/)
```suggestion
- [@article@JVM languages](https://www.whizlabs.com/blog/jvm-languages/)
- [@article@ GraalVM](https://www.graalvm.org/)
- [@feed@Explore top posts about JVM](https://app.daily.dev/tags/jvm?ref=roadmapsh)
```

2024-07-01 09:33 UTC, dansholds commented on src/data/roadmaps/java/content/101-java-advanced-topics/106-how-jvm-works.md
> +- [@article@ GraalVM](https://www.graalvm.org/)
```suggestion
- [@video@How JVM works?](https://youtu.be/G1ubVOl9IBw)
- [@article@JVM languages](https://www.whizlabs.com/blog/jvm-languages/)
- [@article@ GraalVM](https://www.graalvm.org/)
- [@feed@Explore top posts about JVM](https://app.daily.dev/tags/jvm?ref=roadmapsh)
```

2024-07-01 09:34 UTC, dansholds approved these changes
LGTM Now 👍

2024-07-01 09:34 UTC, merged