Add 12 in demand FE skills guide
kamranahmedse/developer-roadmap pull request #6029
Opened 2024-07-04 15:01 UTC by dansholds

Guide added with all associated image incl the new "add the of image at the top of the image" style.

<img width="1095" alt="Screenshot 2024-07-04 at 16 01 09" src="https://github.com/kamranahmedse/developer-roadmap/assets/25537601/8ad07c1e-1be8-4383-86df-699099079adb">

2024-07-05 09:33 UTC, Kordrad commented on src/pages/frontend/developer-skills.astro
> +  permalink={guide.frontmatter.excludedBySlug}
```suggestion
  permalink={guideData.excludedBySlug}
```
this should be a better reference

2024-07-05 09:38 UTC, Kordrad commented
I suggest adding useful links to roadmaps at the end of the article. Here are some of 
- https://roadmap.sh/frontend
- https://roadmap.sh/best-practices/frontend-performance
- https://roadmap.sh/angular
- https://roadmap.sh/react
- https://roadmap.sh/vue
- https://roadmap.sh/javascript

2024-07-05 09:38 UTC, dansholds commented on src/pages/frontend/developer-skills.astro
> +  permalink={guide.frontmatter.excludedBySlug}
@Kordrad thanks but this is how the permalink is set in all of our guide pages, so we leave it as it is atm since it works fine 👍

2024-07-07 17:20 UTC, kamranahmedse requested changes
Rename the file to `data/guides/frontend-developer-skills.md`

2024-07-08 15:11 UTC, merged