Update types--validation@UNlvRp6k3_RDoTAAIEfJ1.md
kamranahmedse/developer-roadmap pull request #6225
Opened 2024-07-25 04:33 UTC by Primis1

Add description for Next.JS Types & Validation node

comment:
Guys you did help me much in the past, so I'm grateful and think u're cool

2024-07-25 07:46 UTC, dansholds requested changes
Thanks for the kind words!

Let's keep this content to one concise paragraph and don't forget to add

`Learn more from the following resources`

Before the content links.

Remember to check the contribution docs and other topics in the project.

2024-07-25 15:30 UTC, Primis1 commented
Thank you for a review, did the article formatting and tiny fixes in spelling, hope it is going to work now)

2024-07-27 00:32 UTC, Primis1 commented
Thank you for a review, did the article formatting and tiny fixes in spelling, hope it is going to work now)

2024-07-31 10:55 UTC, kamranahmedse commented on src/data/roadmaps/react/content/types--validation@UNlvRp6k3_RDoTAAIEfJ1.md
> +- [@article@When Use Zod](https://www.totaltypescript.com/when-should-you-use-zod)
```suggestion
# Types & Validation

**Typescript** provides a static type system that helps you in avoiding mistakes during the development and provides other features (e.g. IDE support) that help you improve your productivity. 

One thing you should note is that TypeScript can only help you avoid mistakes during the development. We can't rely on it to validate a client's input. **Zod** is a powerful validation library that allows us to validate: form input, local storage, API contracts and much more using their typesafe implementation.

Visit the following resources to learn more:

- [@article@What is TypeScript and why would I use it in place of JavaScript?](https://stackoverflow.com/questions/12694530/what-is-typescript-and-why-would-i-use-it-in-place-of-javascript)
- [@article@When Use Zod](https://www.totaltypescript.com/when-should-you-use-zod)
```

2024-07-31 10:58 UTC, merged