Script that updates the repo ranking
kamranahmedse/developer-roadmap pull request #6674
Opened 2024-08-18 18:10 UTC by pyoneerC

We could use an automation to get the ranking of the repository.

_Originally posted by @siamonas in https://github.com/kamranahmedse/developer-roadmap/issues/6658#issuecomment-2295224476_

Draft because I have no idea how to changes variables in a `.astro` with the script, help appreciated.

2024-08-18 20:52 UTC, kamranahmedse requested changes

2024-08-18 20:52 UTC, kamranahmedse commented on .github/workflows/ranking.yml
> +name: Check and update GitHub Ranking in page
I would rather recommend doing this during the build, [just like we get the discord member count](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/lib/discord.ts).

2024-08-18 20:56 UTC, siamonas commented on .github/workflows/ranking.yml
> +name: Check and update GitHub Ranking in page
Sounds good!!

@pyoneerC If you'd like to tackle this on your own, that's great! Otherwise, I'd be happy to help or take it on for you.

2024-08-19 17:36 UTC, pyoneerC commented
Nice @siamonas

2024-08-19 17:36 UTC, closed without merging