Draft: Improved Docker Roadmap. 🌨️
kamranahmedse/developer-roadmap pull request #7029
Opened 2024-09-07 08:09 UTC by offensive-vk

## This Pull Request is a work in progress. Kindly ignore for now.

**Thanks.**

Nothing to see here lol

2024-09-09 15:24 UTC, dansholds commented on src/data/roadmaps/docker/content/104-data-persistence/101-volume-mounts.md
> +> For an in-depth exploration of the `-v` and `--mount` flags, consult Docker's official guide on .
```suggestion
```

2024-09-09 15:26 UTC, dansholds requested changes
This is really good work but lets try to keep the files to a single concise paragraph where possible.

2024-09-09 16:39 UTC, offensive-vk commented
Sure thing, daniel
I will try to minimize the overall content.

Thanks

2024-09-18 14:50 UTC, dansholds commented
@offensive-vk please remove all file creations and moves as its not as simple as just doing that. JSON and/or larger changes would need to be made i.e. creating a new node on the roadmap.

If we keep this PR to simple copy and link changes then we can get it merged.

2024-09-19 09:01 UTC, dansholds commented on src/data/roadmaps/docker/content/107-container-registries/101-dockerhub-alt.md
> +[Amazon Elastic Container Registry (ECR)](https://aws.amazon.com/ecr/) is a fully-managed Docker container registry by Amazon Web Services (AWS) that simplifies the process of storing, managing, and
Again, remove links in the main content (I know you didn't put them here but you made changes to the file)

2024-09-19 09:04 UTC, dansholds commented on src/data/roadmaps/docker/content/index.md
> +Welcome to the Docker Roadmap! This roadmap is designed to help you navigate the world of Docker and learn the essential concepts and commands. Whether you're a beginner or an experienced Docker user
This won't be displayed anywhere.

2024-09-19 09:04 UTC, dansholds requested changes
A few final things to clean up (would be easy multiple smaller PRs)

2024-09-19 12:10 UTC, offensive-vk commented on src/data/roadmaps/docker/content/107-container-registries/100-dockerhub.md
> +[DockerHub](https://hub.docker.com/) is a cloud-based registry service provided by Docker Inc. It is the default public container registry where you can store, manage, and distribute your Docker imag
They were already there 😂

2024-09-19 12:14 UTC, offensive-vk commented
Sorry for this giant pull request.

I'll keep it as little as possible.

2024-09-20 08:04 UTC, merged