Redis Roadmap Content
kamranahmedse/developer-roadmap pull request #7229
Opened 2024-09-25 12:56 UTC by dansholds

2024-09-26 07:58 UTC, offensive-vk commented
Bro watch out for this one [#7227](https://github.com/kamranahmedse/developer-roadmap/pull/7227).

2024-09-26 08:06 UTC, dansholds commented
> Bro watch out for this one [#7227](https://github.com/kamranahmedse/developer-roadmap/pull/7227).

I'm not afraid of a merge conflict, I welcome them.

2024-09-26 08:11 UTC, offensive-vk commented
> > Bro watch out for this one [#7227](https://github.com/kamranahmedse/developer-roadmap/pull/7227).
> 
> I'm not afraid of a merge conflict, I welcome them.

## Woah ☠️

2024-10-02 14:03 UTC, kulterryan commented
I've added some content

2024-10-07 10:23 UTC, kamranahmedse commented on src/data/roadmaps/redis/content/pubsub@9W_jaK1DSEZHRKdPcUM7h.md
> +Pub/Sub in Redis is a powerful messaging paradigm that allows for real-time communication between clients through a publish/subscribe model. In this system, publishers send messages to specific chann
```suggestion
# Pub/Sub

Pub/Sub in Redis is a powerful messaging paradigm that allows for real-time communication between clients through a publish/subscribe model. In this system, publishers send messages to specific channels without knowing who, if anyone, will receive them. Subscribers, on the other hand, express interest in particular channels and receive messages published to those channels instantly. This decouples the message producers from the consumers, facilitating flexible and scalable communication. Key commands in this model include `PUBLISH` for sending messages, `SUBSCRIBE` for listening to channels, and `UNSUBSCRIBE` for stopping the reception of messages.

Visit the following resources to learn more:

- [@official@Pub/Sub in Redis](https://redis.io/docs/latest/develop/interact/pubsub/)
```

2024-10-07 10:29 UTC, kamranahmedse requested changes

2024-10-07 10:29 UTC, kamranahmedse commented on src/data/roadmaps/redis/content/redis-enterprise@8lyXDuZJ-KHl4v2_8Ew1h.md
> +
Missing resources

2024-10-07 10:29 UTC, kamranahmedse commented on src/data/roadmaps/redis/content/redis-modules@hLIT00Iz7rV56ZBIUhWYn.md
> +- [@official@Turn Redis into a Multi-Model Database](https://redis.io/resources/modules-redis-labs-turns-redis-multi-model-database/)
These resources cover module development API an AI integration, links here should be to the individual modules that are mentioned above.

2024-10-07 10:30 UTC, kamranahmedse commented on src/data/roadmaps/redis/content/redis-enterprise@8lyXDuZJ-KHl4v2_8Ew1h.md
> +
```suggestion
```

2024-10-07 10:31 UTC, kamranahmedse commented on src/data/roadmaps/redis/content/redis-modules@hLIT00Iz7rV56ZBIUhWYn.md
> +- [@official@Turn Redis into a Multi-Model Database](https://redis.io/resources/modules-redis-labs-turns-redis-multi-model-database/)
```suggestion
```

2024-10-07 10:31 UTC, merged