Improved Android Roadmap.
kamranahmedse/developer-roadmap pull request #7236
Opened 2024-09-26 08:10 UTC by offensive-vk

## Description

*Under Construction...*

This PR improves the Overall Android Roadmap.

2024-09-26 08:28 UTC, offensive-vk commented
@dansholds , how many files can i modify in this PR? (Current 15)
I wanna keep it less time consuming for you this time. 😉

2024-09-26 08:47 UTC, dansholds commented
> @dansholds , how many files can i modify in this PR? (Current 15) I wanna keep it less time consuming for you this time. 😉

As many as you want, your last PR was clean 🤙🏻

2024-09-26 08:53 UTC, offensive-vk commented
Thankyou @dansholds , but I will be reviewing and going through each file in `Android Roadmap` alphabetically. So its gonna be a lot of modified files (i.e 90+). I will be :

- Adding Links
- Adding / Updating Content
- Adding Anchors
- Fixing Formatting

So will that be fine for ya?

2024-09-26 12:29 UTC, dansholds commented
> Thankyou @dansholds , but I will be reviewing and going through each file in `Android Roadmap` alphabetically. So its gonna be a lot of modified files (i.e 90+). I will be :
> 
>     * Adding Links
> 
>     * Adding / Updating Content
> 
>     * Adding Anchors
> 
>     * Fixing Formatting
> 
> 
> So will that be fine for ya?

Go for it.

2024-09-28 03:46 UTC, offensive-vk commented
@dansholds bro, have a look 🙌

2024-09-30 10:47 UTC, dansholds commented on src/data/roadmaps/android/content/animations@Xn1VQ-xOT67ZfJJTM4r1p.md
> +
why?

2024-09-30 10:47 UTC, dansholds commented on src/data/roadmaps/android/content/apollo-android@ww0fTbdXwVr-QIOClU7ng.md
> +- [@opensource@GraphQL for Android](https://github.com/apollographql/apollo-kotlin)
```suggestion
- [@opensource@apollographql/apollo-kotlin - GraphQL for Android](https://github.com/apollographql/apollo-kotlin)
```

2024-09-30 10:49 UTC, offensive-vk commented on src/data/roadmaps/android/content/animations@Xn1VQ-xOT67ZfJJTM4r1p.md
> +
+1 +1 ???
I don't understand

2024-09-30 10:49 UTC, offensive-vk commented
I'll fix them real soon.

2024-09-30 10:53 UTC, dansholds commented on src/data/roadmaps/android/content/basics-of-kotlin@jl1FsQ5-WGKeFyaILNt_p.md
> +Kotlin's syntax is more concise than Java, which means less code to write and read, and fewer opportunities for errors. It provides several high-level features like lambdas, coroutines and higher ord
one paragraph rather than three please

2024-09-30 10:54 UTC, offensive-vk commented on src/data/roadmaps/android/content/basics-of-kotlin@jl1FsQ5-WGKeFyaILNt_p.md
> +Kotlin's syntax is more concise than Java, which means less code to write and read, and fewer opportunities for errors. It provides several high-level features like lambdas, coroutines and higher ord
got it m8

2024-09-30 10:57 UTC, dansholds commented on src/data/roadmaps/android/content/buttons@WhfzFOUpm0DFEj7Oeq21R.md
> +
This isn't in line with our styling, lets let the links do the talking for this

2024-09-30 10:59 UTC, dansholds commented on src/data/roadmaps/android/content/chucker@7RKN1FNtRE_BE6QeAQrKb.md
> +- [@opensource@Chucker](https://github.com/ChuckerTeam/chucker)
```suggestion
- [@opensource@ChuckerTeam/chucker - Chucker On GitHub](https://github.com/ChuckerTeam/chucker)
```

2024-09-30 10:59 UTC, offensive-vk commented on src/data/roadmaps/android/content/buttons@WhfzFOUpm0DFEj7Oeq21R.md
> +
aight

2024-09-30 11:09 UTC, offensive-vk commented
Finallyyy, it's your time to shine @dansholds 😉

2024-09-30 11:28 UTC, dansholds commented on src/data/roadmaps/android/content/rxkotlin@4h37WBpYxRRyw9oH8ge7o.md
> +- [@opensource@RxKotlin](https://github.com/ReactiveX/RxKotlin)
```suggestion
- [@opensource@ReactiveX/RxKotlin - RxKotlin on GitHub](https://github.com/ReactiveX/RxKotlin)
```

2024-09-30 11:29 UTC, dansholds requested changes
I've left some comments to address

2024-10-01 13:31 UTC, merged

2024-10-01 13:32 UTC, kamranahmedse commented
Thank you @offensive-vk