Add a link to "Learn Git Branching" tutorial to "Branching Basics" topic in "Git & Github" roadmap & rename file in "Backend" roadmap content.
kamranahmedse/developer-roadmap pull request #7250
Opened 2024-09-27 13:54 UTC by iahmadgad

I added a link to [**Learn Git Branching**](https://learngitbranching.js.org/) tutorial to **Branching Basics** topic in **Git & Github** roadmap.

And I've found a file called `god-design-patterns%406XIWO0MoE-ySl4qh_ihXa.md` in the **Backend** roadmap content, I renamed it to `design-patterns%406XIWO0MoE-ySl4qh_ihXa.md`.
I also noticed that this file shares the same id with a file called `gof-design-patterns%406XIWO0MoE-ySl4qh_ihXa.md`.
So I suggest merging the two files into one file or Adding the first file as **Design Patterns** topic in the **Backend** roadmap, because it's not even showing there.

2024-09-27 14:10 UTC, dansholds requested changes
leave the `god` file, its redundant, it was replaced by a direct link (blue button), remove the changes to the file and just leave in the git link additions

2024-09-27 14:43 UTC, iahmadgad commented
I am sorry for the question, but what does `god` stand for? Is it an acronym for "**G**ang of **D**esign"?

2024-09-27 14:53 UTC, dansholds commented
> I am sorry for the question, but what does `god` stand for? Is it an acronym for "**G**ang of **D**esign"?

It doesn't stand for anything in this context, originally it was a misspelt file name

2024-09-27 21:20 UTC, arikchakma approved these changes

2024-09-30 10:44 UTC, dansholds approved these changes

2024-09-30 10:44 UTC, merged