add new references to learn component lifecycles
kamranahmedse/developer-roadmap pull request #7319
Opened 2024-10-03 16:41 UTC by VANSH3104

The previous references for component lifecycles were outdated as they focused on the class component paradigm. This PR updates the documentation to include a more relevant reference that explains the lifecycle methods in the context of functional components, aligning with modern React practices. https://github.com/kamranahmedse/developer-roadmap/issues/6771

2024-10-03 16:43 UTC, VANSH3104 commented
@dansholds, I have made a proper pull request. I apologize for the inconvenience caused by the previous one.

2024-10-04 02:56 UTC, offensive-vk commented on src/data/roadmaps/react/content/component-lifecycle@8OBlgDRUg-CTgDXY-QHyO.md
> +- [@official@Class Component](https://react.dev/reference/react/Component)
Official links must have higher priority, then the others and 2 article links are sufficient.

2024-10-04 03:06 UTC, offensive-vk commented on src/data/roadmaps/react/content/component-lifecycle@8OBlgDRUg-CTgDXY-QHyO.md
There should be no links in main para, just keep the links below if required.
In the mean time, have a thorough understanding of our [contributing guidelines](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md).

2024-10-04 03:11 UTC, offensive-vk commented
Lastly, please refrain from pinging maintainers, all PR will be actioned.

2024-10-04 08:22 UTC, dansholds requested changes
I know you didn't add but please remove the main body link.

2024-10-04 10:13 UTC, VANSH3104 commented
i gave it a article tag because other tags don't hold on it

2024-10-08 11:15 UTC, dansholds approved these changes

2024-10-08 11:15 UTC, merged