Chibuike 19/add ai engineer content
kamranahmedse/developer-roadmap pull request #7349
Opened 2024-10-05 13:08 UTC by chibuike-19

Added contents to five topics in Ai engineer roadmap: 

- [x] adding-end-user-ids-in-promts
- [x] ai agents usecase
- [x] ai agents
- [x] ai code editor
- [x] chroma

2024-10-05 14:42 UTC, kamranahmedse requested changes
Thanks @chibuike-19 -- appreciate the PR!

This roadmap is a little different than the other roadmaps; each item in the roadmap could mean different things so I would recommend understanding the context in which the given topic is mentioned in the roadmap and then adding resources.

2024-10-05 14:42 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/adding-end-user-ids-in-prompts@4Q5x2VCXedAWISBXUIyin.md
> +- [@video@Prompt Management 101 - Full Guide for AI Engineers](https://youtu.be/Qddc_DNo9qY?si=l4_BlFDmOs7Ibgid)
This topic is about sending end user ids to Open AI. There is [only this resource](https://platform.openai.com/docs/guides/safety-best-practices/end-user-ids) and text from that which we can add.

<img width="1040" alt="image" src="https://github.com/user-attachments/assets/5ff417c5-ad56-4118-ae38-3a9c03d28180">

2024-10-05 14:42 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/ai-agents@9XCxilAQ7FRet7lHQr1gE.md
> +-[@article@How to Build AI Agents with LangGraph: A Step-by-Step Guide](https://medium.com/@lorevanoudenhove/how-to-build-ai-agents-with-langgraph-a-step-by-step-guide-5d84d9c7e832)
Let's add this resource instead.

```suggestion
-[@article@Building an AI Agent Tutorial - LangChain](https://python.langchain.com/docs/tutorials/agents/)
```

2024-10-05 14:42 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/ai-code-editors@XcKeQfpTA5ITgdX51I4y-.md
> +-[@article@Build an AI code assistant with Pipet Code Agent](https://ai.google.dev/gemini-api/tutorials/pipet-code-agent)
It doesn't have to be learning resources always. In such cases, it can be examples.

```suggestion
# AI Code Editors

AI code editors are development tools that leverage artificial intelligence to assist software developers in writing, debugging, and optimizing code. These editors go beyond traditional syntax highlighting and code completion by incorporating machine learning models, natural language processing, and data analysis to understand code context, generate suggestions, and even automate portions of the software development process.

Visit the following resources to learn more:

- [@website@Cursor - The AI Code Editor](https://www.cursor.com/)
- [@website@Bolt - Prompt, run, edit, and deploy full-stack web apps](https://bolt.new)
- [@website@Replit - Build Apps using AI](https://replit.com/ai)
- [@website@v0 - Build Apps with AI](https://v0.dev)
```

2024-10-05 14:42 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/chroma@dSd2C9lNl-ymmCRT9_ZC3.md
> +-[@video@Chroma - Vector Database for LLM Applications | OpenAI integration](https://youtu.be/Qs_y0lTJAp0?si=Z2-eSmhf6PKrEKCW)
```suggestion
# Chroma

Chroma is an open-source vector database and AI-native embedding database designed to handle and store large-scale embeddings and semantic vectors. It is used in applications that require fast, efficient similarity searches, such as natural language processing (NLP), machine learning (ML), and AI systems dealing with text, images, and other high-dimensional data.

Visit the following resources to learn more:

-[@official@Chroma](https://www.trychroma.com/)
-[@article@Chroma Tutorials](https://lablab.ai/tech/chroma)
-[@video@Chroma - Chroma - Vector Database for LLM Applications](https://youtu.be/Qs_y0lTJAp0?si=Z2-eSmhf6PKrEKCW)
```

2024-10-06 17:41 UTC, chibuike-19 commented
Thanks @kamranahmedse, would follow your suggestions and make the right changes to the PR

2024-10-06 18:20 UTC, chibuike-19 commented
I've updated my PR with your suggestions @kamranahmedse

2024-10-08 11:33 UTC, dansholds commented on src/data/roadmaps/ai-engineer/content/agents-usecases@778HsQzTuJ_3c9OSn5DmH.md
> +In AI engineering, "agents" refer to autonomous systems or components that can perceive their environment, make decisions, and take actions to achieve specific goals. Agents often interact with exter
The explanation of what Agents are is unnecessary here given this topic's location on the roadmap.

2024-10-08 11:33 UTC, dansholds commented on src/data/roadmaps/ai-engineer/content/adding-end-user-ids-in-prompts@4Q5x2VCXedAWISBXUIyin.md
> +```
This is not in line with the examples in the contribution guides.

2024-10-08 11:35 UTC, dansholds commented on src/data/roadmaps/ai-engineer/content/ai-code-editors@XcKeQfpTA5ITgdX51I4y-.md
> +- [@website@v0 - Build Apps with AI](https://v0.dev)
"website" is not a tag, use "official".

Bolt and v0 are also not AI Code Editors.

2024-10-08 11:36 UTC, dansholds requested changes
as per my comments.

2024-10-11 00:12 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/adding-end-user-ids-in-prompts@4Q5x2VCXedAWISBXUIyin.md
> +```
We don't need to add this detail.

```suggestion
```

2024-10-11 00:12 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/agents-usecases@778HsQzTuJ_3c9OSn5DmH.md
> +In AI engineering, "agents" refer to autonomous systems or components that can perceive their environment, make decisions, and take actions to achieve specific goals. Agents often interact with exter
```suggestion
```

2024-10-11 00:14 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/agents-usecases@778HsQzTuJ_3c9OSn5DmH.md
> +-[@video@The Complete Guide to Building AI Agents for Beginners](https://youtu.be/MOyl58VF2ak?si=-QjRD_5y3iViprJX)
```suggestion

AI Agents have a variety of usecases ranging from customer support, workflow automation, cybersecurity, finance, marketing and sales, and more.

Visit the following resources to learn more:

- [@article@Top 15 Use Cases Of AI Agents In Business](https://www.ampcome.com/post/15-use-cases-of-ai-agents-in-business)
-[@article@A Brief Guide on AI Agents: Benefits and Use Cases](https://www.codica.com/blog/brief-guide-on-ai-agents/)
-[@video@The Complete Guide to Building AI Agents for Beginners](https://youtu.be/MOyl58VF2ak?si=-QjRD_5y3iViprJX)
```

2024-10-11 00:16 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/ai-code-editors@XcKeQfpTA5ITgdX51I4y-.md
> +- [@website@v0 - Build Apps with AI](https://v0.dev)
`website` [_is_ a valid tag](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/components/CustomRoadmap/CustomRoadmap.tsx#L11)

2024-10-11 00:17 UTC, merged