Devops Roadmap: GitHub action & nginx resource added
kamranahmedse/developer-roadmap pull request #7350
Opened 2024-10-05 13:29 UTC by coder7475

This pull request add resource links to devops roadmap. They are follows:

- On github actions, course video: `GitHub Actions Certification – Full Course to PASS the Exam`
- On nginx, article: `Basic NGINX Setup: Ubuntu Guide to a Functional and Secure Website Serving`

2024-10-08 11:37 UTC, dansholds commented on src/data/roadmaps/devops/content/github-actions@JnWVCS1HbAyfCJzGt-WOH.md
> +- [@course@GitHub Actions Certification – Full Course to PASS the Exam](https://www.youtube.com/watch?v=Tz7FsunBbfQ&t=2396s)
Attention to detail, you're linking the video to start 2396 seconds in rather than from the beginning.

2024-10-08 11:38 UTC, dansholds requested changes
As per my comment

2024-10-09 02:56 UTC, coder7475 commented
Sorry about that. Fixed @dansholds

2024-10-10 10:12 UTC, dansholds approved these changes

2024-10-10 10:13 UTC, merged