Complete AI Engineer Roadmap
kamranahmedse/developer-roadmap pull request #7508
Opened 2024-10-17 09:16 UTC by dansholds

All topics have content and at least 2 links.

Top level (Yellow) topics don't have links and the sub topics do all the "talking".

2024-10-17 22:44 UTC, kamranahmedse requested changes
We need to look at the context in which any given term is mentioned. 

Also this roadmap is more about AI implementation so there shouldn't be any algorithmic, or theoretical implementation details or articles linked.

2024-10-17 22:44 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/manual-implementation@6xaRB34_g0HGt-y1dGYXR.md
> +Manual intervention refers to the process where human input is needed to guide, correct, or supervise the actions of the AI. This can include tasks like fine-tuning model outputs, handling exceptions
This should be discussing following:

Services like [Open AI functions](https://platform.openai.com/docs/guides/function-calling) and Tools or [Vercel's AI SDK](https://sdk.vercel.ai/docs/foundations/tools) make it really easy to make SDK agents however it is a good idea to learn how these tools work under the hood. You can also create fully custom implementation of agents using by implementing custom loop.

There is a [video series in Scrimba's AI Engineer path](https://v2.scrimba.com/the-ai-engineer-path-c02v?via=roadmap) that covers this in depth.

2024-10-17 22:44 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/mongodb-atlas@j6bkm0VUgLkHdMDDJFiMC.md
> +- [@video@What is MongoDB Atlas?](https://www.youtube.com/watch?v=1EaOihoxyoE)
This should be about MongoDB Atlas' usage as a Vector database and not MongoDB atlas. We can remove the link to MongoDB roadmap as well.

https://www.mongodb.com/products/platform/atlas-vector-search

2024-10-17 22:44 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/multimodal-ai-usecases@sGR9qcro68KrzM8qWxcH8.md
> +- [@video@Unlocking innovative generative AI use cases with text and multimodal embeddings](https://www.youtube.com/watch?v=2M43pIOo77Y)
We can replace both of these links with just this link from huggingface:
https://huggingface.co/learn/computer-vision-course/en/unit4/multimodal-models/a_multimodal_world

2024-10-17 22:44 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/multimodal-ai@W7cKPt_UxcUgwp8J6hS4p.md
> +- [@article@What Is Multimodal AI? A Complete Introduction](https://www.splunk.com/en_us/blog/learn/multimodal-ai.html)
Add the following link from hugging face at the top

https://huggingface.co/learn/computer-vision-course/en/unit4/multimodal-models/a_multimodal_world

2024-10-17 22:44 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/supabase@9kT7EEQsbeD2WDdN9ADx7.md
> +- [@video@Supabase in 100 Seconds](https://www.youtube.com/watch?v=zBZgdTb-dns)
This text and links should be about [Vector implementation of Supabase](https://supabase.com/vector) and how to use that and nothing else.

2024-10-17 22:44 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/using-sdks-directly@WZVW8FQu6LyspSKm1C_sl.md
> +Using SDKs directly to implement Retrieval-Augmented Generation (RAG) allows developers to seamlessly integrate retrieval and generation components into their applications. SDKs provide pre-built fun
This text should just say:

While tools like Langchain and LlamaIndex make it easy to implement RAG, you don't have to necessarily learn and use them. If you know about the different steps of implementing RAG you can simply do it all yourself e.g. do the chunking using [`@langchain/textsplitters` package](https://js.langchain.com/docs/how_to/#text-splitters), create embeddings using any LLM e.g. use OpenAI Embedding API through their SDK, save the embeddings to any vector database e.g. if you are using [Supabase Vector DB](https://supabase.com/vector), you can use their SDK and similarly you can use the relevant SDKs for the rest of the steps as well.

2024-10-17 22:44 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/using-sdks-directly@WZVW8FQu6LyspSKm1C_sl.md
> +- [@article@Build a retrieval augmented generation (RAG) AI app using SDKs](https://liblab.com/docs/tutorials/rag-with-sdk/)
This looks more like promotion of liblab, we can remove this.

2024-10-17 22:44 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/using-sdks-directly@WZVW8FQu6LyspSKm1C_sl.md
> +- [@article@Retrieval Augmented Generation (RAG) with Pinecone and Vercel's AI SDK](https://www.pinecone.io/learn/context-aware-chatbot-with-vercel-ai-sdk/)
Let's remove this as well and rather add links to different SDKs and packages user can use (e.g. the ones I mentioned in my comment above).

2024-10-17 22:44 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/video-understanding@TxaZCtTCTUfwCxAJ2pmND.md
> +- [@article@Video Understanding](https://paperswithcode.com/task/video-understanding)
This should be less theoretical and talk more in context of Multimodal AI and using existing models (e.g. Open AI Vision API etc)

2024-10-17 22:44 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/what-is-an-ai-engineer@GN6SnI7RXIeW8JeD-qORW.md
> +- [@video@AI Engineers- What Do They Do?](https://www.youtube.com/watch?v=y8qRq9PMCh8&t=1s)
We can remove this video since it is a bit too long and covers various unrelated aspects.

```suggestion
```

2024-10-17 22:44 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/performing-similarity-search@ZcbRPtgaptqKqWBgRrEBU.md
> +- [@article@What is Similarity Search & How Does it work?](https://www.truefoundry.com/blog/similarity-search)
Copied from my other comment:

Indexing is mentioned in context of vector databases and RAG here. The two nodes "Indexing Embeddings" and "Performing Similarity Search" under "Implement Vector Search" should be about :

- how embeddings are stored in a vector database first (i.e. indexing embeddings)
- how similarity search is performed by convering user's query to an embedding first and then searching in vector DB (i.e. similarity search)

2024-10-17 22:44 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/popular-open-source-models@97eu-XxYUH9pYbD_KjAtA.md
> +- [@opensource@OpenAI Whisper](https://github.com/openai/whisper)
This list will keep changing. Instead of mentioning and linking to individual models it is better to link to some articles mentioning popular opensource models e.g. 

https://zapier.com/blog/best-llm/

2024-10-17 22:44 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/semantic-search@eMfcyBxnMY_l_5-8eg6sD.md
> +- [@video@What is Semantic Search? Cohere](https://www.youtube.com/watch?v=fFt4kR4ntAA)
Copied from my other comment:

Indexing is mentioned in context of vector databases and RAG here. The two nodes "Indexing Embeddings" and "Performing Similarity Search" under "Implement Vector Search" should be about :

- how embeddings are stored in a vector database first (i.e. indexing embeddings)
- how similarity search is performed by convering user's query to an embedding first and then searching in vector DB (i.e. similarity search)

2024-10-18 08:18 UTC, dansholds commented on src/data/roadmaps/ai-engineer/content/data-classification@06Xta-OqSci05nV2QMFdF.md
> +- [@article@Simplifying Data Classification for Businesses Using AI](https://www.one-beyond.com/simplifying-data-classification-for-businesses-using-ai/)
I've added the link but this topic is nesting in Embeddings so I thought the copy was relevant?

2024-10-18 21:56 UTC, kamranahmedse requested changes

2024-10-18 21:56 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/image-understanding@fzVq4hGoa2gdbIzoyY1Zp.md
> +- [@course@Introduction to Image Understanding](https://www.cs.utoronto.ca/~fidler/teaching/2019/CSC420.html)
This link is not relevant
```suggestion
```

2024-10-18 21:56 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/anomaly-detection@AglWJ7gb9rTT2rMkstxtk.md
> +- [@video@Anomoly 101](https://www.youtube.com/watch?v=mhSFyXbCaPM)
These other links are not relevant

```suggestion
- [@article@Anomoly in Embeddings](https://ai.google.dev/gemini-api/tutorials/anomaly_detection)
```

2024-10-18 21:56 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/chunking@mX987wiZF7p3V_gExrPeX.md
> +- [@article@Chunk large documents for vector search solutions in Azure AI Search](https://learn.microsoft.com/en-us/azure/search/vector-search-how-to-chunk-documents)
```suggestion
- [@article@Understanding LangChain's RecursiveCharacterTextSplitter](https://dev.to/eteimz/understanding-langchains-recursivecharactertextsplitter-2846)
```

2024-10-18 21:56 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/data-classification@06Xta-OqSci05nV2QMFdF.md
> +- [@article@Simplifying Data Classification for Businesses Using AI](https://www.one-beyond.com/simplifying-data-classification-for-businesses-using-ai/)
These links are not relevant

```suggestion
```

2024-10-18 21:56 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/inference@KWjD4xEPhOOYS51dvRLd2.md
> +- [@article@Inference vs Training](https://www.cloudflare.com/learning/ai/inference-vs-training/)
```suggestion
- [@article@Inference vs Training](https://www.cloudflare.com/learning/ai/inference-vs-training/)
- [@article@What is Machine Learning Inference?](https://hazelcast.com/glossary/machine-learning-inference/)
- [@article@What is Machine Learning Inference? An Introduction to Inference Approaches](https://www.datacamp.com/blog/what-is-machine-learning-inference)
```

2024-10-18 21:56 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/manual-implementation@6xaRB34_g0HGt-y1dGYXR.md
> +Manual implementation often involves using tools and functions that allow developers to define specific functions or actions that an AI model can invoke, providing a structured way to extend the mode
```suggestion
Services like [Open AI functions](https://platform.openai.com/docs/guides/function-calling) and Tools or [Vercel's AI SDK](https://sdk.vercel.ai/docs/foundations/tools) make it really easy to make SDK agents however it is a good idea to learn how these tools work under the hood. You can also create fully custom implementation of agents using by implementing custom loop.
```

2024-10-18 21:56 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/mongodb-atlas@j6bkm0VUgLkHdMDDJFiMC.md
> +- [@video@What is MongoDB Atlas?](https://www.youtube.com/watch?v=1EaOihoxyoE)
```suggestion
- [@official@Vector Search in MongoDB Atlas](https://www.mongodb.com/products/platform/atlas-vector-search)
```

2024-10-18 21:56 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/video-understanding@TxaZCtTCTUfwCxAJ2pmND.md
> +- [@article@Video Understanding](https://paperswithcode.com/task/video-understanding)
These articles do not talk about "Video Understanding" in the context of Multimodal AI.

```suggestion
```

2024-10-18 21:56 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/performing-similarity-search@ZcbRPtgaptqKqWBgRrEBU.md
> +- [@article@What is Similarity Search & How Does it work?](https://www.truefoundry.com/blog/similarity-search)
```suggestion
```

2024-10-18 21:56 UTC, kamranahmedse commented on src/data/roadmaps/ai-engineer/content/popular-open-source-models@97eu-XxYUH9pYbD_KjAtA.md
> +Popular open-source models include BERT for NLP tasks like text classification and question answering, GPT-Neo and GPT-J as alternatives to GPT-3 for text generation, and Stable Diffusion for creatin
As mentioned in my previous comment, we don't need to mention any LLMs here because they will keep changing.

```suggestion
Open-source large language models (LLMs) are models whose source code and architecture are publicly available for use, modification, and distribution. They are built using machine learning algorithms that process and generate human-like text, and being open-source, they promote transparency, innovation, and community collaboration in their development and application.
```

2024-10-18 22:01 UTC, merged