Adding 2 videos links to Aws Roadmap - EC2 and VPC topics
kamranahmedse/developer-roadmap pull request #7533
Opened 2024-10-19 02:15 UTC by focarica

First commit is adding a link to aws official video that give us a resume of what is ec2 and his vantages. Its a short video so i think its good to people to get a _fast_ knowledge of uses of ec2 and _why_ use this.

Second commit is adding a link to freecodecamp video that covers practically everything of vpc service.

2024-10-20 09:54 UTC, dansholds requested changes

2024-10-20 09:54 UTC, dansholds commented on src/data/roadmaps/aws/content/101-ec2/index.md
> +- [@video@Introduction to Amazon EC2](https://www.youtube.com/watch?v=TsRBftzZsQo)
This video is 9 years old, I'm sure there are more up to date resources available.

2024-10-20 12:24 UTC, focarica commented on src/data/roadmaps/aws/content/101-ec2/index.md
> +- [@video@Introduction to Amazon EC2](https://www.youtube.com/watch?v=TsRBftzZsQo)
made an edit and put another video more recent

2024-10-22 09:33 UTC, dansholds approved these changes

2024-10-22 09:34 UTC, merged