Linux
kamranahmedse/developer-roadmap pull request #7541
Opened 2024-10-20 09:58 UTC by Debajyati

## Roadmap URL
https://roadmap.sh/linux
## Nodes
![vim](https://github.com/user-attachments/assets/85a55b99-6a35-420a-9f85-d13147e47dc8)
![Bootloaders](https://github.com/user-attachments/assets/03ffdb90-c461-436f-bab2-55be12df15fe)
![Mounts](https://github.com/user-attachments/assets/db85ff46-2ddc-480e-92c7-0630f3a9e385)
![Shell Programming and Debugging in Bash](https://github.com/user-attachments/assets/9ea5f800-90f3-4fe9-9de8-470291f67da4)
## What I Have Done
> As Hacktoberfest attracts a lot of contributors (which is awesome), it does require a more rigid and strictly enforced set of guidelines than the average contribution.
>
>These are as follows:
>
>1. No single file contributions, please contribute to a minimum of two.

- Improved the content of the nodes - `shell programming` ,`vim` and `bootloaders`. 
- Added relevant resource links to the nodes - `mounts`, `bootloaders`, `shell programming`, `debugging`, `vim`

2024-10-21 09:17 UTC, dansholds requested changes
lets keep this just to adding links, you're adding more copy to old content that already doesn't abide by the newer contribution guidelines.

2024-10-21 15:28 UTC, Debajyati commented
Okay. Just as you command. Sir! 🫡

2024-10-21 15:46 UTC, Debajyati commented
Kindly review the changes again!

2024-10-21 18:28 UTC, offensive-vk commented
So many youtube links and playlists in `114-shell-programming/index.md`?, topics links are too similar and content should be only in one para where possible.

2024-10-21 18:50 UTC, Debajyati commented
> So many youtube links and playlists in `114-shell-programming/index.md`?, topics links are too similar and content should be only in one para where possible.

@offensive-vk done!

2024-10-22 05:05 UTC, offensive-vk commented
Lastly, a proper pr title would be beneficial too.

2024-10-22 09:22 UTC, dansholds commented on src/data/roadmaps/linux/content/101-editing-files/100-vim.md
> +- [@article@Learn Vimscript The Hard Way](https://learnvimscriptthehardway.stevelosh.com/)
```suggestion
- [@article@Vim Cheat Sheet](https://vim.rtorr.com/)
- [@course@Learn Vimscript The Hard Way](https://learnvimscriptthehardway.stevelosh.com/)
```

2024-10-22 09:23 UTC, dansholds commented on src/data/roadmaps/linux/content/114-shell-programming/100-debugging.md
> +- [@article@Debugging a Bash Script](https://www.baeldung.com/linux/debug-bash-script)
```suggestion
```

2024-10-22 09:24 UTC, dansholds commented on src/data/roadmaps/linux/content/114-shell-programming/index.md
> +- [@article@9 Evil Bash Commands Explained](https://dev.to/devmount/9-evil-bash-commands-explained-4k5e)
```suggestion

- [@video@Bash Scripting on Linux - YT Playlist](https://youtube.com/playlist?list=PLT98CRl2KxKGj-VKtApD8-zCqSaN2mD4w&si=MSehStqnhSqgoMSj)
```

2024-10-22 09:24 UTC, dansholds approved these changes

2024-10-22 09:25 UTC, merged