Improve Blockchain Roadmap
kamranahmedse/developer-roadmap pull request #7557
Opened 2024-10-22 14:24 UTC by offensive-vk

> [!TIP]
> Blockchain Roadmap - https://roadmap.sh/blockchain

- Fix Topic Link Anchors
- Fix Topic Link Types
- Fix Topic Link Text
- Format Every Content
- Add More Links
- Add Topic Content
- Fix Deprecated Content
- Remove Deprecated Topic Links

This PR is intended to improve the Blockchain Roadmap as it lacks fresh or *refreshing* content and few more topic links.

Status: *Under Construction* ⚒️

2024-10-22 17:27 UTC, dansholds commented
@offensive-vk theres no need to open 3 draft PRs at once

2024-10-23 09:08 UTC, dansholds commented
> I like draft PRs. And I am helping you right, (I'm gonna open more real soon)

You can make the changes without opening Draft PRs, just create the PR when it's complete.

2024-10-24 09:05 UTC, dansholds requested changes

2024-10-24 09:05 UTC, dansholds commented on src/data/roadmaps/blockchain/content/ethersjs@i-ltfXPTCu3WaBo-xaN05.md
> -- [@feed@Explore top posts about JavaScript](https://app.daily.dev/tags/javascript?ref=roadmapsh)
Don't removed partnered content

2024-10-24 09:05 UTC, dansholds commented on src/data/roadmaps/blockchain/content/general-blockchain-knowledge@bA4V_9AbV3uQi3qrtLWk0.md
> +- [@article@What is Blockchain?](https://www.wired.com/story/guide-blockchain/)
Change to either "What is the Blockchain" or "What is a Blockchain"

2024-10-24 09:31 UTC, offensive-vk commented
Sure thing, dan
I'll review at night.

2024-10-24 09:32 UTC, offensive-vk commented
Hey, @dansholds, what's this hacktoberfest thing and what about its label in here?

2024-10-24 10:40 UTC, offensive-vk commented on src/data/roadmaps/blockchain/content/applications-and-uses@WD2JH4X4tEE4J0W0XFQ_4.md
> +# Application and Uses of Blockchain technology
Sure.

2024-10-24 12:42 UTC, dansholds commented
> Hey, @dansholds, what's this hacktoberfest thing and what about its label in here?

https://hacktoberfest.com/

2024-10-24 12:45 UTC, dansholds approved these changes

2024-10-24 12:46 UTC, merged

2024-10-24 12:50 UTC, offensive-vk commented
bro 😭😭