📃 Image Prompting - In Place Edits (2023, Q2 -> 2024, Q4)
kamranahmedse/developer-roadmap pull request #7571
Opened 2024-10-24 17:19 UTC by iPoetDev

Update topic / sub topics from May 2023 to Oct 2024

- data: `src/data/roadmaps/prompt-engineering/content/108-image-prompting`

- why: Sub topics were empty of content, with only links.

- modify topics: 
   - add content 
       - 100-style-modifers.md
       - 101-quality boosters.md
       - 102-weighted-terms.md
       - 103-deformed-generations.md
   - add links
       - 102-weighted-terms.md

2024-10-24 17:21 UTC, iPoetDev commented
Context: Hacktober submission.
Part of a series: Update entire Prompt Engineering roadmap.
#first-time-PR in Open Source, via fork

2024-10-25 04:05 UTC, offensive-vk commented on src/data/roadmaps/prompt-engineering/content/108-image-prompting/100-style-modifiers.md
> +
```suggestion

Visit the following resources to learn more:

- [@article@Style Modifiers](https://learnprompting.org/docs/image_prompting/style_modifiers)

```

2024-10-25 04:05 UTC, offensive-vk commented on src/data/roadmaps/prompt-engineering/content/108-image-prompting/101-quality-boosters.md
> +- [@article@Quality Boosters - learnprompting.org](https://learnprompting.org/docs/image_prompting/quality_boosters)
```suggestion
Visit the following resources to learn more:

- [@article@Quality Boosters - learnprompting.org](https://learnprompting.org/docs/image_prompting/quality_boosters)
```

2024-10-25 04:06 UTC, offensive-vk commented on src/data/roadmaps/prompt-engineering/content/108-image-prompting/102-weighted-terms.md
> +---
```suggestion
Visit the following resources to learn more:
```

2024-10-25 04:06 UTC, offensive-vk commented on src/data/roadmaps/prompt-engineering/content/108-image-prompting/103-deformed-generations.md
> +- [@article@Fix Deformed Generations](https://learnprompting.org/docs/image_prompting/fix_deformed_generations)
```suggestion
Visit the following resources to learn more:

- [@article@Fix Deformed Generations](https://learnprompting.org/docs/image_prompting/fix_deformed_generations)
```

2024-10-25 04:08 UTC, offensive-vk reviewed
Your first pr is really good, but first, please have a good look of our contributing guidelines here. https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#adding-content

Thankyou for your contributions. 🙌

2024-10-25 07:12 UTC, dansholds commented
> Your first pr is really good, but first, please have a good look of our contributing guidelines here. https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#adding-content
> 
> Thankyou for your contributions. 🙌

@offensive-vk please stop reviewing other peoples PR's and saying "our contributing guidelines", this gives the impression that you're a **core team member** and can cause confusion in other contributors.

@iPoetDev Our contribution guides state a single and concise paragraph for the content and the real power comes from the links that are added, the following is an example of a fully loaded topic:

```
# Redis

Redis is an open-source, in-memory data structure store known for its speed and versatility. It supports various data types, including strings, lists, sets, hashes, and sorted sets, and provides functionalities such as caching, session management, real-time analytics, and message brokering. Redis operates as a key-value store, allowing for rapid read and write operations, and is often used to enhance performance and scalability in applications. It supports persistence options to save data to disk, replication for high availability, and clustering for horizontal scaling. Redis is widely used for scenarios requiring low-latency access to data and high-throughput performance.

Learn more from the following resources:

[@official@Link 1](https:/google.com)
[@article@Link 2](https:/google.com)
[@article@Link 3](https:/google.com)
[@course@Link 4](https:/google.com)
[@course@Link 5](https:/google.com)
[@video@Link 6](https:/google.com)
[@video@Link 7](https:/google.com)
[@video@Link 8](https:/google.com)
```

2024-10-25 07:12 UTC, dansholds requested changes
Requesting changes as per my above comment.

2024-10-25 10:08 UTC, iPoetDev commented
@dansholds 

Understood about a single paragraph intent (as intended in Q4 2024). However, in push back, the content from May 2023 as not info designed in this way.

My stratagem was to extend the current content and fill in the gaps. (Expand).

I get the approach to single paragraph (as it can reduce maintenance and content variability/revision load). 

It is a thing of several days' effort that I have expanded and edits for 54 topics, and was in the process of refining the content in VSCode before commit.

So I will seek some more interaction with you via other channels to get a good formulation/balance between efforts given and effort desired.

I can do the links, BTW>

2024-10-25 18:16 UTC, dansholds commented
@iPoetDev, Thanks Charles, this is much more in line 👍🏻

2024-10-25 18:16 UTC, dansholds approved these changes

2024-10-25 18:16 UTC, merged

2024-10-25 19:46 UTC, iPoetDev commented
Thank you very much. My first every OS merge accept.

2024-10-25 21:46 UTC, iPoetDev commented
Light Admin: Wrong commit message on [8d7672e](https://github.com/kamranahmedse/developer-roadmap/pull/7571/commits/8d7672e)

```

📃 docs, data (Image Prompting) Update Topic/Sub Topics - In Place Edits.

- intent: Update topic from May 2023 to Oct 2024

- data: src/data/roadmaps/prompt-engineering/content/
   - 📂108-image-prompting

- add: New content 
102-weighted-terms.md,100-style-modifers.md,101-quality-boosters.md,103-defomed-generations.md
---

Co-authored-by: [@iPoetDev](https://github.com/iPoetDev) <ipoetdev-github-no-reply@outlook.com>
```