Update read.me
kamranahmedse/developer-roadmap pull request #835
Opened 2021-01-13 15:55 UTC by JulioSergioFS

#### What roadmap does this PR target?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### Please acknowledge the items listed below

- [ ] I have discussed this contribution and got a go-ahead in an issue before opening this pull request.
- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this PR.

#### Enter the details about the contribution

Update the read.me to have a translation to the titles and the descriptions,  instead of just having the roadmaps translated, and be more similar to the original one.

2021-01-14 11:30 UTC, luca-weinert approved these changes

2021-01-16 06:10 UTC, vandroid1444 approved these changes

2021-01-16 06:15 UTC, vandroid1444 requested changes

2021-01-16 06:15 UTC, vandroid1444 commented on translations/portuguese/readme.md
> -> Roadmap to becoming a web developer in 2021
translations/portuguese/readme.md

2021-01-21 04:08 UTC, sm694824 commented
Front end roadmap
Backend roadmap

2021-01-27 11:35 UTC, habib500 approved these changes

2021-01-27 11:37 UTC, habib500 approved these changes

2021-01-29 07:37 UTC, sheekka approved these changes

2021-01-29 12:10 UTC, mary902 approved these changes

2021-02-02 05:37 UTC, merged